#version: "3"
#
services:
  redis:
    image: redis:alpine
#    container_name: redis_server
    ports:
      - "6379:6379"
  order_service:
    build:
      context: ./order_service
      dockerfile: Dockerfile
#    container_name: order_service
    ports:
      - "50051:50051"

  restaurant_service:
    build:
      context: ./restaurant_service
      dockerfile: Dockerfile
#    container_name: restaurant_service
    ports:
      - "50052:50052"

  delivery_service:
    build:
      context: ./delivery_service
      dockerfile: Dockerfile
#    container_name: delivery_service
    ports:
      - "50053:50053"
