# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'order_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13order_service.proto\x12\rorder_service\"L\n\x11PlaceOrderRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\r\n\x05items\x18\x02 \x03(\t\x12\x13\n\x0btotal_price\x18\x03 \x01(\x01\"6\n\x12PlaceOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\")\n\x15GetOrderStatusRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"^\n\x16GetOrderStatusResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\r\n\x05items\x18\x03 \x03(\t\x12\x13\n\x0btotal_price\x18\x04 \x01(\x01\"&\n\x12\x43\x61ncelOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"7\n\x13\x43\x61ncelOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2\x96\x02\n\x0cOrderService\x12Q\n\nPlaceOrder\x12 .order_service.PlaceOrderRequest\x1a!.order_service.PlaceOrderResponse\x12]\n\x0eGetOrderStatus\x12$.order_service.GetOrderStatusRequest\x1a%.order_service.GetOrderStatusResponse\x12T\n\x0b\x43\x61ncelOrder\x12!.order_service.CancelOrderRequest\x1a\".order_service.CancelOrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLACEORDERREQUEST']._serialized_start=38
  _globals['_PLACEORDERREQUEST']._serialized_end=114
  _globals['_PLACEORDERRESPONSE']._serialized_start=116
  _globals['_PLACEORDERRESPONSE']._serialized_end=170
  _globals['_GETORDERSTATUSREQUEST']._serialized_start=172
  _globals['_GETORDERSTATUSREQUEST']._serialized_end=213
  _globals['_GETORDERSTATUSRESPONSE']._serialized_start=215
  _globals['_GETORDERSTATUSRESPONSE']._serialized_end=309
  _globals['_CANCELORDERREQUEST']._serialized_start=311
  _globals['_CANCELORDERREQUEST']._serialized_end=349
  _globals['_CANCELORDERRESPONSE']._serialized_start=351
  _globals['_CANCELORDERRESPONSE']._serialized_end=406
  _globals['_ORDERSERVICE']._serialized_start=409
  _globals['_ORDERSERVICE']._serialized_end=687
# @@protoc_insertion_point(module_scope)
