# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import restaurant_service_pb2 as restaurant__service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in restaurant_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RestaurantServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateMenu = channel.unary_unary(
                '/restaurant_service.RestaurantService/UpdateMenu',
                request_serializer=restaurant__service__pb2.UpdateMenuRequest.SerializeToString,
                response_deserializer=restaurant__service__pb2.UpdateMenuResponse.FromString,
                _registered_method=True)
        self.AcceptOrder = channel.unary_unary(
                '/restaurant_service.RestaurantService/AcceptOrder',
                request_serializer=restaurant__service__pb2.AcceptOrderRequest.SerializeToString,
                response_deserializer=restaurant__service__pb2.AcceptOrderResponse.FromString,
                _registered_method=True)
        self.RejectOrder = channel.unary_unary(
                '/restaurant_service.RestaurantService/RejectOrder',
                request_serializer=restaurant__service__pb2.RejectOrderRequest.SerializeToString,
                response_deserializer=restaurant__service__pb2.RejectOrderResponse.FromString,
                _registered_method=True)


class RestaurantServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateMenu(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RestaurantServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateMenu': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMenu,
                    request_deserializer=restaurant__service__pb2.UpdateMenuRequest.FromString,
                    response_serializer=restaurant__service__pb2.UpdateMenuResponse.SerializeToString,
            ),
            'AcceptOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptOrder,
                    request_deserializer=restaurant__service__pb2.AcceptOrderRequest.FromString,
                    response_serializer=restaurant__service__pb2.AcceptOrderResponse.SerializeToString,
            ),
            'RejectOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectOrder,
                    request_deserializer=restaurant__service__pb2.RejectOrderRequest.FromString,
                    response_serializer=restaurant__service__pb2.RejectOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'restaurant_service.RestaurantService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('restaurant_service.RestaurantService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RestaurantService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateMenu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant_service.RestaurantService/UpdateMenu',
            restaurant__service__pb2.UpdateMenuRequest.SerializeToString,
            restaurant__service__pb2.UpdateMenuResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant_service.RestaurantService/AcceptOrder',
            restaurant__service__pb2.AcceptOrderRequest.SerializeToString,
            restaurant__service__pb2.AcceptOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejectOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant_service.RestaurantService/RejectOrder',
            restaurant__service__pb2.RejectOrderRequest.SerializeToString,
            restaurant__service__pb2.RejectOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
