# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: restaurant_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'restaurant_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18restaurant_service.proto\x12\x12restaurant_service\"W\n\x11UpdateMenuRequest\x12\x15\n\rrestaurant_id\x18\x01 \x01(\t\x12+\n\x05items\x18\x02 \x03(\x0b\x32\x1c.restaurant_service.MenuItem\"$\n\x12UpdateMenuResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"M\n\x08MenuItem\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\"=\n\x12\x41\x63\x63\x65ptOrderRequest\x12\x15\n\rrestaurant_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\"7\n\x13\x41\x63\x63\x65ptOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"=\n\x12RejectOrderRequest\x12\x15\n\rrestaurant_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\"7\n\x13RejectOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2\xb0\x02\n\x11RestaurantService\x12[\n\nUpdateMenu\x12%.restaurant_service.UpdateMenuRequest\x1a&.restaurant_service.UpdateMenuResponse\x12^\n\x0b\x41\x63\x63\x65ptOrder\x12&.restaurant_service.AcceptOrderRequest\x1a\'.restaurant_service.AcceptOrderResponse\x12^\n\x0bRejectOrder\x12&.restaurant_service.RejectOrderRequest\x1a\'.restaurant_service.RejectOrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'restaurant_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPDATEMENUREQUEST']._serialized_start=48
  _globals['_UPDATEMENUREQUEST']._serialized_end=135
  _globals['_UPDATEMENURESPONSE']._serialized_start=137
  _globals['_UPDATEMENURESPONSE']._serialized_end=173
  _globals['_MENUITEM']._serialized_start=175
  _globals['_MENUITEM']._serialized_end=252
  _globals['_ACCEPTORDERREQUEST']._serialized_start=254
  _globals['_ACCEPTORDERREQUEST']._serialized_end=315
  _globals['_ACCEPTORDERRESPONSE']._serialized_start=317
  _globals['_ACCEPTORDERRESPONSE']._serialized_end=372
  _globals['_REJECTORDERREQUEST']._serialized_start=374
  _globals['_REJECTORDERREQUEST']._serialized_end=435
  _globals['_REJECTORDERRESPONSE']._serialized_start=437
  _globals['_REJECTORDERRESPONSE']._serialized_end=492
  _globals['_RESTAURANTSERVICE']._serialized_start=495
  _globals['_RESTAURANTSERVICE']._serialized_end=799
# @@protoc_insertion_point(module_scope)
