# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: delivery_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'delivery_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64\x65livery_service.proto\x12\x10\x64\x65livery_service\":\n\x13\x41ssignDriverRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x11\n\tdriver_id\x18\x02 \x01(\t\"=\n\x14\x41ssignDriverResponse\x12\x15\n\rassignment_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"?\n\x1bUpdateDeliveryStatusRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"@\n\x1cUpdateDeliveryStatusResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"0\n\x1bGetDriverAssignmentsRequest\x12\x11\n\tdriver_id\x18\x01 \x01(\t\"Y\n\x1cGetDriverAssignmentsResponse\x12\x39\n\x0b\x61ssignments\x18\x01 \x03(\x0b\x32$.delivery_service.DeliveryAssignment\"M\n\x12\x44\x65liveryAssignment\x12\x15\n\rassignment_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t2\xde\x02\n\x0f\x44\x65liveryService\x12]\n\x0c\x41ssignDriver\x12%.delivery_service.AssignDriverRequest\x1a&.delivery_service.AssignDriverResponse\x12u\n\x14UpdateDeliveryStatus\x12-.delivery_service.UpdateDeliveryStatusRequest\x1a..delivery_service.UpdateDeliveryStatusResponse\x12u\n\x14GetDriverAssignments\x12-.delivery_service.GetDriverAssignmentsRequest\x1a..delivery_service.GetDriverAssignmentsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'delivery_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASSIGNDRIVERREQUEST']._serialized_start=44
  _globals['_ASSIGNDRIVERREQUEST']._serialized_end=102
  _globals['_ASSIGNDRIVERRESPONSE']._serialized_start=104
  _globals['_ASSIGNDRIVERRESPONSE']._serialized_end=165
  _globals['_UPDATEDELIVERYSTATUSREQUEST']._serialized_start=167
  _globals['_UPDATEDELIVERYSTATUSREQUEST']._serialized_end=230
  _globals['_UPDATEDELIVERYSTATUSRESPONSE']._serialized_start=232
  _globals['_UPDATEDELIVERYSTATUSRESPONSE']._serialized_end=296
  _globals['_GETDRIVERASSIGNMENTSREQUEST']._serialized_start=298
  _globals['_GETDRIVERASSIGNMENTSREQUEST']._serialized_end=346
  _globals['_GETDRIVERASSIGNMENTSRESPONSE']._serialized_start=348
  _globals['_GETDRIVERASSIGNMENTSRESPONSE']._serialized_end=437
  _globals['_DELIVERYASSIGNMENT']._serialized_start=439
  _globals['_DELIVERYASSIGNMENT']._serialized_end=516
  _globals['_DELIVERYSERVICE']._serialized_start=519
  _globals['_DELIVERYSERVICE']._serialized_end=869
# @@protoc_insertion_point(module_scope)
