# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import delivery_service_pb2 as delivery__service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in delivery_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeliveryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AssignDriver = channel.unary_unary(
                '/delivery_service.DeliveryService/AssignDriver',
                request_serializer=delivery__service__pb2.AssignDriverRequest.SerializeToString,
                response_deserializer=delivery__service__pb2.AssignDriverResponse.FromString,
                _registered_method=True)
        self.UpdateDeliveryStatus = channel.unary_unary(
                '/delivery_service.DeliveryService/UpdateDeliveryStatus',
                request_serializer=delivery__service__pb2.UpdateDeliveryStatusRequest.SerializeToString,
                response_deserializer=delivery__service__pb2.UpdateDeliveryStatusResponse.FromString,
                _registered_method=True)
        self.GetDriverAssignments = channel.unary_unary(
                '/delivery_service.DeliveryService/GetDriverAssignments',
                request_serializer=delivery__service__pb2.GetDriverAssignmentsRequest.SerializeToString,
                response_deserializer=delivery__service__pb2.GetDriverAssignmentsResponse.FromString,
                _registered_method=True)


class DeliveryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AssignDriver(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDeliveryStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDriverAssignments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeliveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AssignDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignDriver,
                    request_deserializer=delivery__service__pb2.AssignDriverRequest.FromString,
                    response_serializer=delivery__service__pb2.AssignDriverResponse.SerializeToString,
            ),
            'UpdateDeliveryStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDeliveryStatus,
                    request_deserializer=delivery__service__pb2.UpdateDeliveryStatusRequest.FromString,
                    response_serializer=delivery__service__pb2.UpdateDeliveryStatusResponse.SerializeToString,
            ),
            'GetDriverAssignments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDriverAssignments,
                    request_deserializer=delivery__service__pb2.GetDriverAssignmentsRequest.FromString,
                    response_serializer=delivery__service__pb2.GetDriverAssignmentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'delivery_service.DeliveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('delivery_service.DeliveryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeliveryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AssignDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/delivery_service.DeliveryService/AssignDriver',
            delivery__service__pb2.AssignDriverRequest.SerializeToString,
            delivery__service__pb2.AssignDriverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDeliveryStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/delivery_service.DeliveryService/UpdateDeliveryStatus',
            delivery__service__pb2.UpdateDeliveryStatusRequest.SerializeToString,
            delivery__service__pb2.UpdateDeliveryStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDriverAssignments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/delivery_service.DeliveryService/GetDriverAssignments',
            delivery__service__pb2.GetDriverAssignmentsRequest.SerializeToString,
            delivery__service__pb2.GetDriverAssignmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
